import type { Locale } from './locales';

const copy = {
  'en-US': ['On this page', 'More possibilities', 'Frequently asked questions', 'preset layouts', 'videos at once, up to', 'Make it yours', 'Position, size and dividers', 'Try another way to use Split Screen Player', 'Read guide', 'Choose your device', 'Enlarge image', 'Close image', 'View the iPhone / iPad guide', 'View the Android guide', 'iPhone / iPad', 'Android', 'Scan to download'],
  'zh-Hans': ['本文目录', '更多使用方式', '常见问题', '种预设布局', '个视频，最多同时播放', '自由调整', '位置、大小与分割线', '接下来，你还可以这样用', '阅读教程', '选择设备版本', '放大图片', '关闭图片', '查看 iPhone / iPad 教程', '查看 Android 教程', 'iPhone / iPad 版', 'Android 版', '扫码下载'],
  'zh-Hant': ['本文目錄', '更多使用方式', '常見問題', '種預設版面配置', '部影片，最多同時播放', '自由調整', '位置、大小與分隔線', '接下來，你還可以這樣用', '閱讀教學', '選擇裝置版本', '放大圖片', '關閉圖片', '查看 iPhone / iPad 教學', '查看 Android 教學', 'iPhone / iPad 版', 'Android 版', '掃碼下載'],
  ja: ['目次', 'さらに活用する', 'よくある質問', '種類のプリセットレイアウト', '本の動画を同時再生（最大）', '自由にカスタマイズ', '位置・サイズ・区切り線', 'ほかの使い方も試してみましょう', 'ガイドを読む', 'デバイスを選択', '画像を拡大', '画像を閉じる', 'iPhone / iPad のガイドを見る', 'Android のガイドを見る', 'iPhone / iPad 版', 'Android 版', 'スキャンしてダウンロード'],
  ko: ['목차', '더 다양한 활용법', '자주 묻는 질문', '가지 기본 레이아웃', '개 동영상까지 동시 재생', '자유롭게 조정', '위치, 크기 및 구분선', '다른 활용법도 알아보세요', '가이드 읽기', '기기 버전 선택', '이미지 확대', '이미지 닫기', 'iPhone / iPad 가이드 보기', 'Android 가이드 보기', 'iPhone / iPad 버전', 'Android 버전', '스캔하여 다운로드'],
  fr: ['Dans ce guide', 'Aller plus loin', 'Questions fréquentes', 'dispositions prédéfinies', 'vidéos simultanées au maximum', 'À votre mesure', 'Position, taille et séparations', 'Découvrez d’autres façons d’utiliser l’app', 'Lire le guide', 'Choisir votre appareil', 'Agrandir l’image', 'Fermer l’image', 'Voir le guide iPhone / iPad', 'Voir le guide Android', 'iPhone / iPad', 'Android', 'Scanner pour télécharger'],
  de: ['In dieser Anleitung', 'Weitere Möglichkeiten', 'Häufige Fragen', 'vorgefertigte Layouts', 'Videos gleichzeitig, maximal', 'Selbst gestalten', 'Position, Größe und Trennlinien', 'Weitere Möglichkeiten mit Split Screen Player', 'Anleitung lesen', 'Gerät auswählen', 'Bild vergrößern', 'Bild schließen', 'Zur Anleitung für iPhone / iPad', 'Zur Anleitung für Android', 'iPhone / iPad', 'Android', 'Zum Herunterladen scannen'],
  es: ['En esta guía', 'Más posibilidades', 'Preguntas frecuentes', 'diseños predefinidos', 'vídeos simultáneos como máximo', 'A tu medida', 'Posición, tamaño y divisiones', 'Descubre otras formas de usar la app', 'Leer guía', 'Elige tu dispositivo', 'Ampliar imagen', 'Cerrar imagen', 'Ver la guía de iPhone / iPad', 'Ver la guía de Android', 'iPhone / iPad', 'Android', 'Escanear para descargar'],
  'pt-BR': ['Neste guia', 'Mais possibilidades', 'Perguntas frequentes', 'layouts predefinidos', 'vídeos simultâneos, no máximo', 'Do seu jeito', 'Posição, tamanho e divisórias', 'Conheça outras formas de usar o app', 'Ler guia', 'Escolha seu dispositivo', 'Ampliar imagem', 'Fechar imagem', 'Ver o guia para iPhone / iPad', 'Ver o guia para Android', 'iPhone / iPad', 'Android', 'Escanear para baixar'],
} satisfies Record<Locale, string[]>;

export const articleChrome = Object.fromEntries(Object.entries(copy).map(([locale, value]) => {
  const [toc, more, faq, layouts, videos, customize, geometry, related, read, choosePlatform, enlarge, close, iosGuide, androidGuide, iosLabel, androidLabel, scan] = value;
  return [locale, { toc, more, faq, layouts, videos, customize, geometry, related, read, choosePlatform, enlarge, close, iosGuide, androidGuide, iosLabel, androidLabel, scan }];
})) as Record<Locale, { toc: string; more: string; faq: string; layouts: string; videos: string; customize: string; geometry: string; related: string; read: string; choosePlatform: string; enlarge: string; close: string; iosGuide: string; androidGuide: string; iosLabel: string; androidLabel: string; scan: string }>;
